version: "3"

volumes:
  db-data:

services:
  db:
    image: postgres:14-alpine
    container_name: local-test-db
    volumes:
      - ./bin/postgresql:/docker-entrypoint-initdb.d
      - db-data:/var/lib/postgresql/db_development/data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password