version: "3"

volumes:
  db-data:

services:
  db:
    image: postgres:14-alpine
    container_name: timeline-local
    volumes:
      - ./bin/postgresql:/docker-entrypoint-initdb.d
      - db-data:/var/lib/postgresql/timeline_dev/data
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password